 

  version: 2

models:
  - name: fact_table
    description: >
         Combined data from sensors, food, and station snapshots.
         Includes sensor readings, food quantities and prices, and station information.
         
    columns:
      - name: event_id
        description: Event unique id
        data_type: int64      
      - name: temp
        data_type: float
        description: "Temperature recorded by sensors"
      - name: rh
        data_type: float
        description: "Relative humidity recorded by sensors"
      - name: co2
        data_type: float
        description: "Carbon Dioxide recorded by sensors"
      - name: wa
        data_type: float
        description: "Water activity recorded by sensors"
      - name: station
        data_type: string
        description: "Location of the sensor station"
      - name: datetime
        data_type: timestamp
        description: "Timestamp of the sensor reading"
      - name: quantity
        data_type: float
        description: "Quantity of food stored at the station"
      - name: price_unity
        data_type: float
        description: "Price per unit of food"
      - name: price_total
        data_type: float
        description: "Total price of food"
      - name: station_food_type
        data_type: string
        description: "Type of food stored at the station"
